services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dowoDbTech
      MYSQL_DATABASE: dowotech_contact
      //MYSQL_ROUNDCUBE_DATABASE: roundcubemail
      MYSQL_USER: wola
      MYSQL_PASSWORD: wol@kodw

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql     
    networks:
      - dowotech-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: wola
      DB_PASSWORD: wol@kodw
      DB_DATABASE: dowotech_contact
      GITHUB_WEBHOOK_SECRET: jvrZPCCLDfgItbhFKUvS16tSA+0u7Z0YUCylPLpS0EA=
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      dowotech-network:
        aliases:
         - backend

  frontend:
    build:
      context: .
      dockerfile: teckruns/Dockerfile
    restart: always
    image: dowotech-frontend-1
    ports:
      - "8088:80"
    depends_on:
      - backend
    networks:
      - dowotech-network
    container_name: dowotech-frontend-1
    volumes:
         - frontend_build:/frontend_build

  roundcube:
    build:
      context: ./roundcube
      dockerfile: Dockerfile.roundcube
      #image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: always
    ports:
      - "8080:80"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_USER=wola-roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=woladwrcub
      - ROUNDCUBEMAIL_DB_NAME=roundcubemail
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail.dowotech.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.dowotech.com
      - ROUNDCUBEMAIL_SMTP_PORT=587
      #- ROUNDCUBEMAIL_NO_OVERWRITE=1

        #volumes:
      #- ./roundcube/config:/var/www/html/config
         #  - ./roundcube/config/config.docker.inc.php:/var/www/html/config/config.docker.inc.php
        #- ./roundcube/logs:/var/www/html/logs
        #- ./roundcube/temp:/var/www/html/temp

    networks:
      - dowotech-network

    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/dowotech.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/roundcube.conf:/etc/nginx/conf.d/roundcube.conf
      - frontend_build:/var/www/dowotech-frontend/teckruns
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/ssl/certs/dhparam.pem
      - /var/www/letsencrypt:/var/www/letsencrypt
    depends_on:
      - frontend
      - backend
      - roundcube
    networks:
      - dowotech-network

volumes:
  db_data:
  frontend_build:
    #roundcube-logs:
    #roundcube-temp:

networks:
  dowotech-network:
    name: dowotech-network
    driver: bridge